import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "p1",
    name: "Graphic T-Shirt",
    category: "Fashion",
    price: 24.99,
    imageId: "product-1",
    rating: 4.5,
    reviews: 112,
    description: "A stylish and comfortable men's graphic t-shirt made from 100% premium cotton.",
  },
  {
    id: "p2",
    name: "Wireless Headphones",
    category: "Electronics",
    price: 149.99,
    imageId: "product-2",
    rating: 4.8,
    reviews: 245,
    description: "Modern wireless headphones with active noise-cancellation and a 20-hour battery life.",
  },
  {
    id: "p3",
    name: "Quantum Smartphone",
    category: "Electronics",
    price: 699.99,
    imageId: "product-3",
    rating: 4.7,
    reviews: 450,
    description: "A sleek and powerful smartphone with a high-resolution display and a triple-camera system.",
  },
  {
    id: "p4",
    name: "Classic Leather Wallet",
    category: "Accessories",
    price: 49.99,
    imageId: "product-4",
    rating: 4.6,
    reviews: 88,
    description: "A timeless leather wallet with multiple compartments for cards and cash.",
  },
  {
    id: "p5",
    name: "Aviator Sunglasses",
    category: "Accessories",
    price: 79.99,
    imageId: "product-5",
    rating: 4.4,
    reviews: 65,
    description: "Fashionable aviator sunglasses with UV400 protection to keep your eyes safe in style.",
  },
  {
    id: "p6",
    name: "Adventure Backpack",
    category: "Bags",
    price: 89.99,
    imageId: "product-6",
    rating: 4.9,
    reviews: 150,
    description: "A durable and spacious backpack perfect for travel, hiking, or daily commuting.",
  },
  {
    id: "p7",
    name: "Organic Skincare Set",
    category: "Healthcare",
    price: 59.99,
    imageId: "product-7",
    rating: 4.7,
    reviews: 92,
    description: "A complete set of organic skincare products to rejuvenate your skin and give it a healthy glow.",
  },
  {
    id: "p8",
    name: "Pro-Digital Camera",
    category: "Electronics",
    price: 899.99,
    imageId: "product-8",
    rating: 4.8,
    reviews: 180,
    description: "A professional-grade digital camera with a 24MP sensor and 4K video recording capabilities.",
  },
];
